import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Navigation from '../components/NavBar/Navigation'
import { Toaster } from 'sonner';

const roboto = Roboto({
  display: 'swap',
  style: 'normal',
  weight: '700',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'ListingAnime',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navigation></Navigation>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  )
}
